### PR TITLE
Use PR checks to flag successful/unsuccessful deployments

### PR DESCRIPTION
**Pull request by neilbmclaughlin**

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
Still some further work to be done but see https://github.com/nhsuk/gp-finder/pull/202 as an example of using checks to flag successful/unsuccessful deployments.

**Comment by neilbmclaughlin** [comment]
Additional work would be to create a pending status when deployment starts to fit with the other checks.

Might be worth considering whether we turn off travis checks and script our own for the individual bits of CI - build, test, image build and deployments

**Comment by beseven** [comment]
If the check would have @c2s-dev Deployment/rancher — Deployment of nhsuk/gp-finder [ succeeded ](<url-to-pr-deployed>) would look great. The opposite: @c2s-dev Deployment/rancher — Deployment of nhsuk/gp-finder [ failed ](<url-to-project-on-tc>)?

**Comment by neilbmclaughlin** [comment]
@beseven There doesn't seem to be much flexibility of the checks layout in Github so the URL appears as _Details_ with no option to change that but I'll investigate further.

**Review by st3v3nhunt — DISMISSED** [review]
LGTM 👍

**Comment by neilbmclaughlin** [comment]
Added pending status so this should be good to go.

**Review by adamgraves-choices — APPROVED** [review]

**Pull request merged**
